const gameData = [
  { 
    name: 'What Do You Meme?', 
    playerMin: 3, 
    playerMax: 10, 
    ageMin: 17, 
    playTimeMin: 15, 
    playTimeMax: 90, 
    rating: 5.1, 
    category: 'Funny Comparison', 
    image: 'https://media.kohlsimg.com/is/image/kohls/4466678?wid=600&hei=600&op_sharpen=1', 
    description: 'What Do You Meme? is a party card game for the social media generation. Each round, one player takes the role of judge and plays a photo card, after which everyone else plays a caption card to complete the meme. The judge decides the funniest pairing, and whoever played the winning caption card wins the round. Lather, rinse, and repeat.'
  },
  { 
    name: 'Codenames', 
    playerMin: 2, 
    playerMax: 8, 
    ageMin: 14, 
    playTimeMin: 10, 
    playTimeMax: 15, 
    rating: 7.5, 
    category: 'Team', 
    image: 'https://store.ncsml.org/wp-content/uploads/2018/07/Codenames-500x500.png', 
    description: 'Two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their codenames — single-word labels like "disease", "Germany", and "carrot". Yes, carrot. It\'s a legitimate codename. Each spymaster wants their team to identify their agents first...without uncovering the assassin by mistake.\nIn Codenames, two teams compete to see who can make contact with all of their agents first. Lay out 25 cards, each bearing a single word. The spymasters look at a card showing the identity of each card, then take turns clueing their teammates. A clue consists of a single word and a number, with the number suggesting how many cards in play have some association to the given clue word. The teammates then identify one agent they think is on their team; if they\'re correct, they can keep guessing up to the stated number of times; if the agent belongs to the opposing team or is an innocent bystander, the team\'s turn ends; and if they fingered the assassin, they lose the game.'
  },

  {
    name: "UNO",
    playerMin: 2,
    playerMax: 10,
    ageMin: 6,
    playTimeMin: 10,
    playTimeMax: 30,
    rating: 5.5,
    category: "Card",
    image: null,
    description: "Players race to empty their hands and catch opposing players with cards left in theirs, which score points. In turns, players attempt to play a card by matching its color, number, or word to the topmost card on the discard pile. If unable to play, players draw a card from the draw pile, and if still unable to play, they pass their turn. Wild and special cards spice things up a bit."
  },
  {
    name: "The Chameleon",
    playerMin: 3,
    playerMax: 8,
    ageMin: 14,
    playTimeMin: 15,
    playTimeMax: 15,
    rating: 6.6,
    category: "Deception",
    image: null,
    description: "A bluffing deduction game for everyone. Each round involves two missions, depending on whether you’re the Chameleon or not."
  },
  {
    name: "One Night Ultimate Werewolf",
    playerMin: 3,
    playerMax: 10,
    ageMin: 8,
    playTimeMin: 10,
    playTimeMax: 10,
    rating: 7.1,
    category: "Deception",
    image: null,
    description: "One Night Ultimate Werewolf is a fast game for 3-10 players in which everyone gets a role: One of the dastardly Werewolves, the tricky Troublemaker, the helpful Seer, or one of a dozen different characters, each with a special ability."
  },
  {
    name: "Secret Hitler",
    playerMin: 5,
    playerMax: 10,
    ageMin: 13,
    playTimeMin: 45,
    playTimeMax: 45,
    rating: 7.5,
    category: "Deception",
    image: null,
    description: "Secret Hitler is a dramatic game of political intrigue and betrayal set in 1930s Germany."
  },
  {
    name: "Bananagrams",
    playerMin: 1,
    playerMax: 8,
    ageMin: 7,
    playTimeMin: 15,
    playTimeMax: 15,
    rating: 6.4,
    category: "Word",
    image: null,
    description: "Bananagrams is a fast and fun word game that requires no pencil, paper or board."
  },
  {
    name: "Jenga",
    playerMin: 1,
    playerMax: 8,
    ageMin: 6,
    playTimeMin: 20,
    playTimeMax: 20,
    rating: 5.6,
    category: "Dexterity",
    image: null,
    description: "A tower building game."
  },
  {
    name: "The Settlers of Catan",
    playerMin: 3,
    playerMax: 6,
    ageMin: 10,
    playTimeMin: 60,
    playTimeMax: 75,
    rating: 7.1,
    category: "Strategy",
    image: null,
    description: "Embark on a quest to settle the fair isle of Catan! Guide your brave settlers to victory by using clever trading and development."
  },
  {
    name: "Cards Against Humanity",
    playerMin: 4,
    playerMax: 30,
    ageMin: 17,
    playTimeMin: 30,
    playTimeMax: 30,
    rating: 5.8,
    category: "Funny Comparison",
    image: null,
    description: "A party game for horrible people."
  },
  {
    name: "Exploding Kittens",
    playerMin: 2,
    playerMax: 5,
    ageMin: 7,
    playTimeMin: 15,
    playTimeMax: 15,
    rating: 6.1,
    category: "Card",
    image: null,
    description: "Exploding Kittens is a kitty-powered version of Russian Roulette."
  },
  {
    name: "Telestrations",
    playerMin: 4,
    playerMax: 8,
    ageMin: 12,
    playTimeMin: 30,
    playTimeMax: 30,
    rating: 7.4,
    category: "Dexterity",
    image: null,
    description: "Each player begins by sketching a TELESTRATIONS word dictated by the roll of a die."
  },
  {
    name: "Scrabble",
    playerMin: 2,
    playerMax: 4,
    ageMin: 10,
    playTimeMin: 90,
    playTimeMax: 90,
    rating: 6.3,
    category: "Word",
    image: null,
    description: "In this classic word game, players use their seven drawn letter-tiles to form words on the gameboard."
  },
  {
    name: "Catchphrase",
    playerMin: 2,
    playerMax: 4,
    ageMin: 10,
    playTimeMin: 20,
    playTimeMax: 60,
    rating: 6.2,
    category: "Word",
    image: null,
    description: "In this game, each player has a common phrase, which the other players try to guess."
  },
  {
    name: "Cover Your Assets",
    playerMin: 2,
    playerMax: 6,
    ageMin: 8,
    playTimeMin: 15,
    playTimeMax: 45,
    rating: 6.4,
    category: "Card",
    image: null,
    description: "The stakes are high in this high-energy, competitive, and cut-throat, set-collection card game from Grandpa Beck's Games! ... "
  },
  {
    name: "Poetry for Neanderthals",
    playerMin: 2,
    playerMax: 12,
    ageMin: 7,
    playTimeMin: 15,
    playTimeMax: 15,
    rating: 6.7,
    category: "Team",
    image: null,
    description: "Poetry for Neanderthals is a competitive word-guessing game where you can only give clues by speaking in single syllables. ..."
  },
  {
    name: "Skull King",
    playerMin: 2,
    playerMax: 8,
    ageMin: 8,
    playTimeMin: 30,
    playTimeMax: 30,
    rating: 7.5,
    category: "Card",
    image: null,
    description: "Skull King is a trick-taking game similar to Oh Hell!, Wizard, Euchre and Spades, with players needing to state how many tricks they think they'll win each round. ..."
  },
  {
    name: "Apples to Apples",
    playerMin: 4,
    playerMax: 10,
    ageMin: 12,
    playTimeMin: 20,
    playTimeMax: 30,
    rating: 5.8,
    category: "Funny Comparison",
    image: null,
    description: "The party game Apples to Apples consists of two decks of cards: Things and Descriptions. ..."
  },
  {
    name: "Phase 10",
    playerMin: 2,
    playerMax: 6,
    ageMin: 8,
    playTimeMin: 45,
    playTimeMax: 45,
    rating: 5.2,
    category: "Card",
    image: null,
    description: "A rummy-type card game where players compete to be the first to finish completing all ten phases. ..."
  },
  {
    name: "Nertz",
    playerMin: 2,
    playerMax: 6,
    ageMin: 7,
    playTimeMin: 60,
    playTimeMax: 60,
    rating: 6.5,
    category: "Card",
    image: null,
    description: "Nertz, also known widely as Pounce, is a fast paced card game where every player has their own standard deck of cards and engage in a form of multi-player solitaire. ..."
  },
  {
    name: "Dominion",
    playerMin: 2,
    playerMax: 4,
    ageMin: 13,
    playTimeMin: 30,
    playTimeMax: 30,
    rating: 7.6,
    category: "Strategy",
    image: null,
    description: "In Dominion, each player starts with an identical, very small deck of cards. ..."
  }
];

module.exports = gameData;
