const gameData = [
  { name: 'Rolex Submariner', category: 'Sports', subCategory: 'Diver', image: 'https://content.rolex.com/v7/dam/2023-06/upright-c/m124060-0001.png?impolicy=v7-majesty&imwidth=1200' },
  { name: 'Rolex Daytona', category: 'Sports', subCategory: 'Chronograph', image: 'https://m.media-amazon.com/images/I/71PwU1M+poL._AC_UY1000_.jpg' },
  { name: 'Rolex GMT Master II', category: 'Sports', subCategory: 'GMT', image: 'https://cdn11.bigcommerce.com/s-bc02e/images/stencil/1280x1280/products/113323/111295/126710blro__80483.1622656983.jpg?c=2' },
  { name: 'Rolex Datejust', category: 'Dress', subCategory: 'Circular', image: 'https://s.turbifycdn.com/aah/movadobaby/rolex-datejust-36-diamonds-two-tone-unisex-watch-16233-90.jpg' },
  { name: 'Rolex Explorer', category: 'Casual', subCategory: 'Everyday', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ8pdmCRoUT_6DRNIDXjOESDzgk1ZrMUCzYA&usqp=CAU' },
  { name: 'Hamilton Intra Matic', category: 'Sports', subCategory: 'Chronograph', image: 'https://cdn11.bigcommerce.com/s-28d61/images/stencil/1280x1280/products/13532/124465/hamilton-watches-hamilton-american-classic-intra-matic-40mm-blk-dial-mens-watch-h38429730__55518.1661372115.jpg?c=2' },
  { name: 'Hamilton Khaki Mechanical', category: 'Casual', subCategory: 'Field/Pilot', image: 'https://m.media-amazon.com/images/I/81D0hUtxwRL._AC_UY1000_.jpg' },
  { name: 'Hamilton Khaki Automatic', category: 'Casual', subCategory: 'Field/Pilot', image: 'https://www.timescapeusa.com/cdn/shop/products/HAMILTONKhakiFieldh70455133.jpg?v=1672945399https://www.timescapeusa.com/cdn/shop/products/HAMILTONKhakiFieldh70455133.jpg?v=1672945399' },
  { name: 'Zenith El Primero', category: 'Sports', subCategory: 'Chronograph', image: 'https://m.media-amazon.com/images/I/818NIpVe3iL._AC_UY1000_.jpg'},
  { name: 'Omega Speedmaster', category: 'Sports', subCategory: 'Chronograph', image: 'https://http2.mlstatic.com/D_NQ_NP_671799-MCO50693831077_072022-O.webp' },
  { name: 'Omega Seamaster', category: 'Sports', subCategory: 'Diver', image: 'https://m.media-amazon.com/images/I/718PpKHKSML._AC_UY1000_.jpg' },
  { name: 'Omega Aqua Terra', category: 'Casual', subCategory: 'Everyday', image: 'https://s.turbifycdn.com/aah/movadobaby/omega-aqua-terra-231-90-39-21-04-001-51.jpg' },
  { name: 'Omega Constellation', category: 'Dress', subCategory: 'Circular', image: 'https://www.prestigetime.com/images/watches/131.10.29.20.05.001_constellation.jpg' },
  { name: 'Cartier Tank', category: 'Dress', subCategory: 'Rectangular', image: 'https://s.turbifycdn.com/aah/movadobaby/cartier-tank-louis-w1529856-80.jpg' },
  { name: 'Cartier Santos', category: 'Dress', subCategory: 'Rectangular', image: 'https://cdn11.bigcommerce.com/s-28d61/images/stencil/1280x1280/products/14749/142799/cartier-watches-cartier-santos-de-cartier-medium-auto-blue-dial-mens-watch-wssa0063__67022.1702357648.jpg?c=2' },
  { name: 'Patek Philippe Calatrava', category: 'Dress', subCategory: 'Circular', image: 'https://s.turbifycdn.com/aah/movadobaby/patek-philippe-calatrava-7200r-001-42.jpg' },
  { name: 'Jaeger-LeCoultre Reverso', category: 'Dress', subCategory: 'Rectangular', image: 'https://www.prestigetime.com/images/watches/2542540%20reverso.jpg' },
  { name: 'Breitling Superocean', category: 'Sports', subCategory: 'Diver', image: 'https://topperjewelers.com/cdn/shop/products/breitling-superocean-42-sil-br-topper_1200x1200.png?v=1656608566' },
  { name: 'Breitling Premiere B01', category: 'Sports', subCategory: 'Chronograph', image: 'https://www.prestigetime.com/images/watches/rb0118371g1p2-breitling-premier-b01-chronograph-42.jpg' },
  { name: 'Longines Zulu Time', category: 'Sports', subCategory: 'GMT', image: 'https://us.firstclasswatches.com/thumbnails/images/products/product123149-2950_cropped.jpg.thumb_FFFCFA_600x1000.jpg' },
  { name: 'Longines Conquest', category: 'Casual', subCategory: 'Everyday', image: 'https://gemorie.com/wp-content/uploads/2021/03/longines-longines-conquest-mens-water-resistant-watch-stainless-steel-201653.jpg' },
  { name: 'Longines Legend Diver', category: 'Sports', subCategory: 'Diver', image: 'https://m.media-amazon.com/images/I/716lr-Tn3ZL._AC_UY1000_.jpg' },
  { name: 'Tudor 1926', category: 'Casual', subCategory: 'Everyday', image: 'https://s.turbifycdn.com/aah/movadobaby/tudor-1926-41mm-m91650-0005-29.jpg' },
  { name: 'Tudor Royal', category: 'Dress', subCategory: 'Circular', image: 'https://m.media-amazon.com/images/I/61jyLxlClXL._AC_UY1000_.jpg' },
  { name: 'IWC Pilot', category: 'Casual', subCategory: 'Field/Pilot', image: 'https://s.turbifycdn.com/aah/movadobaby/iwc-pilot-s-automatic-36-iw324001-46.jpg' },
];

module.exports = gameData;
